from messaging_processor.consumers.approval_toggle_consumer import ApprovalToggleConsumer
from messaging_processor.consumers.user_type_change_consumer import UserTypeChangeConsumer
from messaging_processor.consumers.sm_deletion_consumer import SMDeletionConsumer
from messaging_processor.consumers.ug_deletion_consumer import UGDeletionConsumer
