# Use root/example as user/password credentials
# make sure to run this command insider for the first time to allow it to be
# connect by outside system  -  update mysql.user set host='%' where user='root'
version: '3.3'
 
services:
  mysql8-service:
    image: public.ecr.aws/lts/mysql:latest
    container_name: mysql8-service
    command: --sql_mode="" --init-file /data/application/init.sql
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: approvals
    ports:
      - 3307:3306
    volumes:
      - ./init.sql:/data/application/init.sql