"""Add ApprovalModuleState table

Revision ID: 1bdd17805a35
Revises: f1e0b90f9c99
Create Date: 2023-03-15 14:55:52.198618

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1bdd17805a35'
down_revision = 'f1e0b90f9c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApprovalModuleState',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('smId', sa.Integer(), nullable=False),
                    sa.Column('enabled', sa.Boolean(), nullable=False),
                    sa.Column('pendingTasks', sa.JSON(), nullable=True),
                    sa.Column('metaData', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('smId')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApprovalModuleState')
    # ### end Alembic commands ###
