"""fix migrations

Revision ID: 47fe70c8b59d
Revises: ea252a0674f7
Create Date: 2023-05-02 09:02:08.326984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47fe70c8b59d'
down_revision = 'ea252a0674f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ApprovalFlow_id', table_name='ApprovalFlow')
    op.create_index(op.f('ix_ApprovalRequest_conversationId'), 'ApprovalRequest', ['conversationId'], unique=False)
    op.create_index(op.f('ix_ApprovalRequest_smId'), 'ApprovalRequest', ['smId'], unique=False)
    op.drop_constraint('ApprovalRequest_ibfk_1', 'ApprovalRequest', type_='foreignkey')
    op.create_foreign_key(None, 'ApprovalRequest', 'ApprovalFlow', ['approvalFlowId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ApprovalStep_ibfk_1', 'ApprovalStep', type_='foreignkey')
    op.create_foreign_key(None, 'ApprovalStep', 'ApprovalFlow', ['approvalFlowId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_ApproverRequestHistory_approvalFlowId', 'ApproverRequestHistory', type_='foreignkey')
    op.alter_column('ApproverRequestHistory', 'approvalFlowId',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'ApproverRequestHistory', 'ApprovalFlow', ['approvalFlowId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ApproverRequestHistory', type_='foreignkey')
    op.alter_column('ApproverRequestHistory', 'approvalFlowId',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_foreign_key('fk_ApproverRequestHistory_approvalFlowId', 'ApproverRequestHistory', 'ApprovalFlow', ['approvalFlowId'], ['id'])
    op.drop_constraint(None, 'ApprovalStep', type_='foreignkey')
    op.create_foreign_key('ApprovalStep_ibfk_1', 'ApprovalStep', 'ApprovalFlow', ['approvalFlowId'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'ApprovalRequest', type_='foreignkey')
    op.create_foreign_key('ApprovalRequest_ibfk_1', 'ApprovalRequest', 'ApprovalFlow', ['approvalFlowId'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ApprovalRequest_smId'), table_name='ApprovalRequest')
    op.drop_index(op.f('ix_ApprovalRequest_conversationId'), table_name='ApprovalRequest')
    op.create_index('ix_ApprovalFlow_id', 'ApprovalFlow', ['id'], unique=False)
    # ### end Alembic commands ###
