"""modify ApproverRequestHistory

Revision ID: b821f7bd126f
Revises: 1bdd17805a35
Create Date: 2023-03-21 13:06:10.959535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b821f7bd126f'
down_revision = '1bdd17805a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Make the existing foreign key column nullable
    op.alter_column('ApproverRequestHistory', 'smApproverId', existing_type=sa.BigInteger(), nullable=True)
    
    # Add a new column to the table
    op.add_column('ApproverRequestHistory', sa.Column('approvalFlowId', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        'fk_ApproverRequestHistory_approvalFlowId',
        'ApproverRequestHistory',
        'ApprovalFlow',
        ['approvalFlowId'],
        ['id']
    )
    # sa.ForeignKeyConstraint(['approvalFlowId'], ['ApprovalFlow.id'], ondelete='CASCADE')

    # Add a new column to the table
    op.add_column('ApproverRequestHistory', sa.Column('createdBy', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the new column from the table
    op.drop_column('ApproverRequestHistory', 'createdBy')
    op.drop_column('ApproverRequestHistory', 'approvalFlowId')
    op.drop_constraint(
        'fk_ApproverRequestHistory_approvalFlowId',
        'ApproverRequestHistory',
        type_='foreignkey'
    )

    # Make the foreign key column non-nullable
    op.alter_column('ApproverRequestHistory', 'smApproverId', existing_type=sa.BigInteger(), nullable=False)
    
    # ### end Alembic commands ###
