"""Store approver type mapping at SM level

Revision ID: c0abedaecc75
Revises: b821f7bd126f
Create Date: 2023-04-06 07:14:40.168605

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0abedaecc75'
down_revision = 'b821f7bd126f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(table_name='SmApprover', column_name='smCollaboratorId', nullable=True,
                    new_column_name='approverExternalId', existing_type=sa.BigInteger())

    op.add_column(table_name='SmApprover', column=sa.Column('approverType', sa.String(length=15), nullable=True))

    op.create_index(index_name='sm_approver_external_id_idx', table_name='SmApprover',
                    columns=['approverExternalId', 'approverId', 'smId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='SmApprover', column_name='approverType')

    op.alter_column(table_name='SmApprover', column_name='approverExternalId', nullable=True,
                    new_column_name='smCollaboratorId')

    op.drop_index('sm_approver_external_id_idx', table_name='SmApprover')
    # ### end Alembic commands ###
