"""create_tables
Revision ID: f1e0b90f9c99
Revises: 
Create Date: 2022-10-06 17:26:33.230019
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e0b90f9c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApprovalFlow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('smId', sa.BigInteger(), nullable=False),
    sa.Column('usergroupId', sa.BigInteger(), nullable=False),
    sa.Column('initialStepId', sa.BigInteger(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('smId', 'name', name='approvalFlow_smId_name_constraint')
    )
    op.create_index(op.f('ix_ApprovalFlow_id'), 'ApprovalFlow', ['id'], unique=False)
    op.create_table('Approver',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('approverExternalId', sa.BigInteger(), nullable=True),
    sa.Column('approverType', sa.String(length=15), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approverExternalId', 'approverType', name='approverExternalId_approverType_constraint'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_Approver_id'), 'Approver', ['id'], unique=False)
    op.create_table('ApprovalStep',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approvalFlowId', sa.BigInteger(), nullable=True),
    sa.Column('nextStepId', sa.BigInteger(), nullable=True),
    sa.Column('createdBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approvalFlowId'], ['ApprovalFlow.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ApprovalStep_id'), 'ApprovalStep', ['id'], unique=False)
    op.create_table('SmApprover',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approverId', sa.BigInteger(), nullable=False),
    sa.Column('smId', sa.BigInteger(), nullable=False),
    sa.Column('smCollaboratorId', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approverId'], ['Approver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approverId', 'smId', name='approverId_smid_constraint')
    )
    op.create_index(op.f('ix_SmApprover_id'), 'SmApprover', ['id'], unique=False)
    op.create_table('ApprovalRequest',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('smId', sa.BigInteger(), nullable=False),
    sa.Column('approvalFlowId', sa.BigInteger(), nullable=True),
    sa.Column('conversationId', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currentStepId', sa.BigInteger(), nullable=True),
    sa.Column('permalink', sa.String(length=200), nullable=True),
    sa.Column('createdBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approvalFlowId'], ['ApprovalFlow.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currentStepId'], ['ApprovalStep.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approvalFlowId', 'conversationId', 'smId', name='approvalFlow_conversation_sm_constraint')
    )
    op.create_index(op.f('ix_ApprovalRequest_id'), 'ApprovalRequest', ['id'], unique=False)
    op.create_table('StepApprover',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approvalStepId', sa.BigInteger(), nullable=False),
    sa.Column('smApproverId', sa.BigInteger(), nullable=False),
    sa.Column('createdBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approvalStepId'], ['ApprovalStep.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smApproverId'], ['SmApprover.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StepApprover_id'), 'StepApprover', ['id'], unique=False)
    op.create_table('ApproverRequestHistory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('smApproverId', sa.BigInteger(), nullable=False),
    sa.Column('approvalRequestId', sa.BigInteger(), nullable=False),
    sa.Column('conversationId', sa.BigInteger(), nullable=False),
    sa.Column('stepId', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=15), nullable=True),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approvalRequestId'], ['ApprovalRequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smApproverId'], ['SmApprover.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ApproverRequestHistory_id'), 'ApproverRequestHistory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ApproverRequestHistory_id'), table_name='ApproverRequestHistory')
    op.drop_table('ApproverRequestHistory')
    op.drop_index(op.f('ix_StepApprover_id'), table_name='StepApprover')
    op.drop_table('StepApprover')
    op.drop_index(op.f('ix_ApprovalRequest_id'), table_name='ApprovalRequest')
    op.drop_table('ApprovalRequest')
    op.drop_index(op.f('ix_SmApprover_id'), table_name='SmApprover')
    op.drop_table('SmApprover')
    op.drop_index(op.f('ix_ApprovalStep_id'), table_name='ApprovalStep')
    op.drop_table('ApprovalStep')
    op.drop_index(op.f('ix_Approver_id'), table_name='Approver')
    op.drop_table('Approver')
    op.drop_index(op.f('ix_ApprovalFlow_id'), table_name='ApprovalFlow')
    op.drop_table('ApprovalFlow')
    # ### end Alembic commands ###