version: 0.2

phases:
  pre_build:
    commands:
      - printenv
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - bash api/ci-cd/build_docker_image_latest.sh approvals api/Dockerfile.buddy